### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by mitchellthomas10**
Bump validation dependency to 0.9.0 to include a formData validation bug fix
(first PR failed in Travis, but it didn't look code related)

### CODE REVIEW

**Comment by mitchellthomas10** [comment]
Is there a set plan to release this?

**Comment by jsdevel** [comment]
@mitchellthomas10 published as `v0.31.2`.

**Comment by Blackbaud-MitchellThomas** [comment]
Thanks a bunch!

**Comment by jsdevel** [comment]
thanks for you contributions @mitchellthomas10 !

**Pull request merged**
