### PR TITLE
Support external schema reference

### PR DESCRIPTION
**Pull request by MugeSo**
See #17 

This works after following PRs are merged & published as new versions and update package.json.

https://github.com/kogosoftwarellc/express-openapi-response-validation/pull/2
https://github.com/kogosoftwarellc/express-openapi-validation/pull/3

### CODE REVIEW

**Comment by jsdevel** [comment]
Looks good!  Can you squash your commits?

**Comment by jsdevel** [comment]
I merged the PR you had open for `express-openapi-validation` and published it as `v0.7.0`.  Can you update package.json to reference it?  Also need `express-openapi-response-validation` to receive `externalSchemas`.

**Comment by MugeSo** [comment]
Ok, I'll squash commits when I update package.json.

**Comment by jsdevel** [comment]
`express-openapi-response-validation` published as `v0.3.0`.  Thanks again @MugeSo !

**Comment by jsdevel** [comment]
Thanks @MugeSo !  Published as `v0.19.0`.  Can you open a PR to add `args.externalSchemas` in the README?

**Comment by MugeSo** [comment]
@jsdevel I'll do that.

**Pull request merged**
