### PR TITLE
Update basePath at request time.

### PR DESCRIPTION
**Pull request by willist**
Handle nested apps (see issue #40) by updating the basePath when the apiDoc is requested.

### CODE REVIEW

**Comment by jsdevel** [comment]
Looks like tests are failing.  Can you take a look?

**Comment by willist** [comment]
It looks like I missed some unstaged changes in the first commit.  Tests are now passing on 4.x and 5.x.  I'll need to dig into the 0.10 and 0.12 failures though.

**Comment by jsdevel** [comment]
also, I'm surprised that this isn't working already.  See https://github.com/kogosoftwarellc/express-openapi/blob/master/index.js#L223

**Comment by willist** [comment]
Okay, it looks like there were two separate issues in my project.

1. The parent app was an instance of Router instead of Application.  Router does not appear to have a mountpath, which is why I wasn't seeing any modification to the basePath.
2. I have several nested applications above express-openapi.  I am serving the api doc at ``/api/nested/v1/api-docs``, where each level of that path is a separate application.  Even when I resolve the first issue by switching from Router to Application, my basePath is ``/nested/v1`` instead of ``/api/nested/v1`` due to limitations of mountpath.

This PR resolves both issues, but is missing unit tests that accurately reflect those issues.  I'll add those in the morning and update this PR.  I'll also look into and fix issues with 0.10 and 0.12.

I've also updated #40 to better explain item 2 above.

**Comment by jsdevel** [comment]
> This PR resolves both issues, but is missing unit tests that accurately reflect those issues. I'll add those in the morning and update this PR. I'll also look into and fix issues with 0.10 and 0.12.

Thanks!  Looking forward to merging this.

**Comment by willist** [comment]
I added test cases and fixed the failures on 0.10 and 0.12.

**Pull request merged**
