### PR TITLE
#82 set apidoc host

### PR DESCRIPTION
**Pull request by XuluWarrior**

### CODE REVIEW

**Comment by XuluWarrior** [comment]
Adding host to the api-docs breaks some tests as the deep compare with the test/fixtures fails.
I'm not sure the best way around this.  
Maybe some flag to enable/disable updating the host?
Or, perhaps only updating the host if the api-docs already has a value for host?

**Comment by jsdevel** [comment]
Would it be possible to update the tests?  I like the idea of verifying the returned host header.

**Comment by XuluWarrior** [comment]
The problem is that wrapping an express app in supertest results in it creating an "ephemeral" port for each test.  Which would mean that the port would change on each run.

I've taken a look and I see two ways around this.
The first is to call app.listen with a fixed port and wrap the listener instead e.g.
```
before(function() {
  app = require('./app.js').listen("54321");
});
```
This is the simplest change but I don't know if we need to be concerned with the possibility that the port might be in use.

The other option is to get the server address from the generated get request and modify the expected json with the host before comparing. e.g.
```
it('should expose <apiDoc>.basePath/api-docs', function(done) {
  var get = request(app)
    .get('/v3/api-docs');
  var host = get.url.match(/\/\/(.+:\d+)\//)[1];
  expectedApiDoc.host = host;
  get
    .expect(200, expectedApiDoc, done);
});
```

**Comment by jsdevel** [comment]
You should be able to set the `Host` header right?

**Comment by XuluWarrior** [comment]
I'm not sure what you mean.  Set Host on which header?

**Comment by XuluWarrior** [comment]
I'm not sure what you mean.  Set Host on which header?

**Comment by jsdevel** [comment]
```
  var get = request(app)
    .set('Host', 'foo.com')
    .get('/v3/api-docs');
  var host = get.url.match(/\/\/(.+:\d+)\//)[1];
  expectedApiDoc.host = host;
```

**Comment by XuluWarrior** [comment]
That works.
I've set Host to "test-host" in all the tests that request api-docs and compare the full result.

**Comment by jsdevel** [comment]
Thanks @XuluWarrior !  This is great!

**Pull request merged**
